package com.soulaim.tech.gles;

public enum TextureID {
    TILESET_UNIT,
    DEFEAT,
    HEALTH_ICON,
    MM_BUTTONS,
    DIFF_BUTTONS,
    NUMBERS,
    PARTICLE,
    LEVEL_ICONS,
    PAUSED,
    OPTIONS_BUTTONS,
    PERFECT,
    BG_FIRE,
    FONT,
    DIRECTIONS,
    ICON_NO_SPELL,

    LEVELTILES,
    DEFAULT,
    GOBLIN_ANIMATION,
    DUCKLING_ANIMATION,
    SPELL_ICONS,
    MAGIC_SYMBOL
}
